### PR TITLE
adding Oath/Yahoo failure story

### PR DESCRIPTION
**Pull request by cruschke**

### CODE REVIEW

**Comment by cruschke** [comment]
did read "Most recent publications on top." too late :-/

**Comment by hjacobs** [comment]
Can you link the YouTube video of the talk instead? I guess the talk conveys more information than what is in the slides.

**Comment by hristobakalov** [comment]
https://www.youtube.com/watch?v=likHm-KHGWQ
Here is the video from the presentation :)

**Comment by hjacobs** [comment]
@cruschke @hristobakalov thanks!

**Pull request merged**
